language: ruby
rvm:
- 2.1

install:
 - gem install "jekyll"
 - gem install "html-proofer"
 - gem install "bundle"

script: 
 - bundle exec jekyll build
 - bundle exec htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

