language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --href-ignore "#" --disable-external