title: zehengl

author: Zeheng Li

email: imzehengl@gmail.com

url: "https://zehengl.github.io"

markdown: kramdown

paginate_path: "/blog/page:num/"
paginate: 10

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-paginate
