title: Zeheng Li

email: imzehengl@gmail.com

description: > #
 A Blog for Zeheng Li, powered by Jekyll, Disqus, Google Analytics, and Github.
 Progarmming/Research bits and pieces.

baseurl: ""

url: "https://zehengl.github.io/"

twitter_username: zehengl

github_username: zehengl

instagram_username: zehengl

linkedin_username: zehengl

wechat_username: zehengl

skype_username: zehengl

facebook_username: zli4u

renren_username: lizeheng1986

qq_username: 51163802

weibo_username: chimaodeyu

youtube_username: cefzhl

markdown: kramdown
