title: ZEHENGL

author: Zeheng Li

email: imzehengl@gmail.com

description: > #
 A blog where Zeheng Li writes about Progarmming/Research bits and pieces, 
 powered by Github, Jekyll, Disqus, Google Analytics & Custom Search Engine, and more.

baseurl: ""

url: "https://zehengl.github.io/"

github_username: zehengl

twitter_username: zehengl

instagram_username: zehengl

facebook_username: zli4u

linkedin_username: zehengl

youtube_username: cefzhl

wechat_username: zehengl

skype_username: zehengl

qq_username: 51163802

web_username: zehengl

wordpress_username: imzehengl

medium_username: zehengl

markdown: kramdown

exclude: [vendor]

gems: 
    - jekyll-sitemap