title: zehengl

footer: >
  Hosted on Github,
  Powered by Jekyll, Google Material Design, Google Custom Search Engine, Disqus, formspree, and more...

author: Zeheng Li

email: imzehengl@gmail.com

url: "https://zehengl.github.io"

markdown: kramdown

paginate_path: "/blog/page:num/"
paginate: 9

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-paginate
