title: ZEHENGL

author: Zeheng Li

email: imzehengl@gmail.com

head_note: > #
 A blog where Zeheng Li writes about Progarmming/Research bits and pieces

foot_note: > #
 Copyright &copy; 2016 &middot; All Rights Reserved &middot; zehengl
baseurl: ""

url: "https://zehengl.github.io/"

github_href: "https://github.com/zehengl"
github_icon: "/assets/svg/icon-github.svg"

twitter_href: "https://twitter.com/zehengl"
twitter_icon: "/assets/svg/icon-twitter.svg"

instagram_href: "https://instagram.com/zehengl"
instagram_icon: "/assets/svg/icon-instagram.svg"

facebook_href: "https://facebook.com/zli4u"
facebook_icon: "/assets/svg/icon-facebook.svg"

linkedin_href: "https://linkedin.com/in/zehengl"
linkedin_icon: "/assets/svg/icon-linkedin.svg"

youtube_href: "https://youtube.com/cefzhl"
youtube_icon: "/assets/svg/icon-youtube.svg"

web_href: "http://lyle.smu.edu/~zehengl"
web_icon: "/assets/svg/icon-web.svg"

wordpress_href: "https://imzehengl.wordpress.com"
wordpress_icon: "/assets/svg/icon-wordpress.svg"

medium_href: "https://medium.com/@zehengl"
medium_icon: "/assets/svg/icon-medium.svg"

rpubs_href: "https://rpubs.com/zehengl"
rpubs_icon: "/assets/svg/icon-rpubs.svg"

orcid_href: "http://orcid.org/0000-0003-1118-0839"
orcid_icon: "/assets/svg/icon-orcid.png"

wechat_href: zehengl
wechat_icon: "/assets/svg/icon-wechat.svg"

skype_href: zehengl
skype_icon: "/assets/svg/icon-skype.svg"

qq_href: 51163802
qq_icon: "/assets/svg/icon-qq.svg"

markdown: kramdown

exclude: [vendor]

gems:
  - jekyll-sitemap
