site_name: zehengl.github.io
site_author: Zeheng Li
theme:
  name: material
  favicon: https://raw.githubusercontent.com/zehengl/logo/main/ZL.png
  logo: https://raw.githubusercontent.com/zehengl/logo/main/ZL.png
  font:
    text: Roboto
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top
repo_name: zehengl.github.io
repo_url: https://github.com/zehengl/zehengl.github.io
copyright: Copyright &copy; 2018 - 2024 Zeheng Li
nav:
  - index.md
  - uses.md
plugins:
  - search
  - tags
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zehengl
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/zehengl
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
