name: pcu
on:
  push:
    branches: [develop]
  schedule:
    - cron: "0 12 * * 1"
jobs:
  refreshDeps:
    runs-on: ubuntu-latest
    steps:
      - uses: zehengl/refresh-python-dependency@main
        with:
          path: requirements-dev.txt
